spring:
  datasource:
    url: jdbc:postgresql://aeropuerto-db.cmlkiwy4w3cp.us-east-1.rds.amazonaws.com:5432/aeropuerto
    username: postgres
    password: ${DB_PASSWORD_AWS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    root: INFO
    org.springframework.security: WARN