spring:
  application:
    name: aeropuertolosprimos   # Nombre lógico de la app (identificación en logs, Spring Cloud, etc.)

  profiles:
    active: dev                 # Activa el perfil "dev" → carga application-dev.yml o propiedades específicas de desarrollo

  docker:
    compose:
      enabled: false            # Desactiva la integración automática con docker-compose (Spring Boot no levanta contenedores)

jwt:
  secret: ${JWT_SECRET}        # Clave secreta para firmar JWT, obtenida de variable de entorno
  expiration: 3600000          # Tiempo de expiración del token en milisegundos (1 hora)